# Generated by Django 5.1.3 on 2024-12-07 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_remove_playermodel_ptname'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermodel',
            name='ptname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newapp.teammodel'),
        ),
    ]
